### PR TITLE
Migrate the main library to use the plugin

### PR DESCRIPTION
**Pull request by edsko**
This PR is WIP, but is migrating the plugin (#61) into the main `large-records` library. Doing this bit by bit, will first clean up the existing library a bit, and then eventually migrate. Creating this draft PR to track the work.

### CODE REVIEW

**Comment by edsko** [comment]
Ok, `large-records-plugin` is now fully integrated into `large-records`, and passes all of the tests in the `large-records` test suite. I've made various changes along the way, see https://github.com/well-typed/large-records/pull/63/commits/b67d3d81c14ef7160f60087f6c6e148570caeed5 for details. As I worked, I also made the coding style conform the rest of the repository; this was of course not essential, but it helped me consider every part.

**Comment by edsko** [comment]
I've tried to preserve as much location information as possible, but within HLS at least this is not working very well.. Opened an issue about that at https://github.com/haskell/haskell-language-server/issues/2779.

**Comment by edsko** [comment]
I've now also updated the benchmarks. Before-and-after comparison for compilation time for the benchmark:

benchmark-01-before-vs-after-timing

And higher-kinded benchmark:

benchmark-03-higherkinded-timing

If we crunch the numbers, we find that replacing TH with a plugin results in roughly a 25% compilation time improvement. This isn't the point of course, but it's nonetheless a nice bonus.

**Comment by edsko** [comment]
@neongreen I think this PR is now ready. I have integrated the plugin now entirely into `large-records` itself, updated the test suite and benchmarks, and made numerous other small changes. I have also added `Monadfix OÜ` to the `LICENSE` file. 

Can you please let me know if this version works for you? If so, I think we can merge this and release it, and then (if it's okay with you) I will write a short blog post about it,  saying that MonadFix and Well-Typed teamed together on this new release.

**Comment by kana-sama** [comment]
Thanks! We will test it tomorrow.

**Comment by avnik** [comment]
@edsko LGTM for b5e56de5e3b132d45cbc4e6cab5c56a80ef5c99d (which I checked)

**Comment by edsko** [comment]
Excellent! Thanks for confirming. I will rebase and release :)

**Comment by edsko** [comment]
And blog post announcement: https://well-typed.com/blog/2022/03/large-records-without-the-quotes/ .

**Pull request merged**
