### PR TITLE
Support ghc 9.6

### PR DESCRIPTION
**Pull request by TristanCacqueray**

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
Well, I haven't tried the change, this simply fix the compilation errors. This depends on: https://github.com/ndmitchell/record-dot-preprocessor/pull/59

**Comment by alexfmpe** [comment]
@edsko would it be possible to get this merged? 
`large-generics` (and dependants) is broken for 9.6+ on nixpkgs and applying this PR over there doesn't work because the merge of #152 gave it conflicts

**Comment by edsko** [comment]
I appreciate the work that @TristanCacqueray did, but it only got us part of the way there. But hopefully I should have an updated PR soon, and then I will make Hackage releases.

**Comment by alexfmpe** [comment]
> Well, after fixing this build, I realized large-records was added transitively by proto3-suite through an optional flags, and it didn't look like this PR was enough, so we disabled the flags.

Oooh hadn't realised that. proto3-suite is also how large-records ends up in my dependency tree, and my current workaround is pointing at this PR, might look into the flag instead.

Anedoctal, but I was using nixpkgs' 9.4 package set until a couple weeks ago and at least with my specific dependencies this PR allows building large-records (and this proto3-suite) on 9.6. 
I'm pointing directly to it, skipping #152, but that requires callCabal2nix, which can't be used in nixpkgs, so no upstreaming option there either.

**Comment by edsko** [comment]
Closed in favour of #156. See discussion and acknowledgements there :)

**Pull request closed without merging**
