### PR TITLE
ANON pattern

### PR DESCRIPTION
**Pull request by kana-sama**
Solution for #104

TODO: normal doc for `assert`. May be there is a better solution than `assert`.

Examples:
```haskell
f ANON{} = ()                                       -- in
f (assert -> _) = ()                                -- out

f ANON{a = a} = a                                   -- in
f (get #a -> a) = a                                 -- out

f ANON{a = a, b = b} = a + b                        -- in
f ((\x -> (get #a x, get #b x)) -> (a, b)) = a + b  -- out

f ANON_F{a = I a} = a                               -- in
f (A.get #a -> I a) = a                             -- out
```

### CODE REVIEW

**Comment by kana-sama** [comment]
@edsko

**Comment by kana-sama** [comment]
I have selected `RowHasField` and `get` instead of `HasField` and `getField` for better type inference.
But we can generate something like
```haskell
f ANON{a = a} = a
f (assert -> (getField "a" -> a)) = a
```
Which will produce `HasField` constraint with correct input type, but I decided that nested view patterns are not cool

**Comment by kana-sama** [comment]
I have selected `RowHasField` and `get` instead of `HasField` and `getField` for better type inference.
But we can generate something like
```haskell
f ANON{a = a} = a
f (assert -> (getField "a" -> a)) = a
```
Which will produce `HasField` constraint with correct input type, but I decided that nested view patterns are not cool

**Comment by sheaf** [comment]
Hi @kana-sama, thanks for the PR. Edsko is away at the moment, but I will take a look next week. Thanks for your patience.

**Review by sheaf — COMMENTED** [review]
Hi @kana-sama. Thanks for taking this on, as I think this is an important feature.

Other than the trivial review comments, here are a few observations.

### Type inference

Type inference seems to work well. It would be worth testing this, but I'm not sure how to do that. Type inference doesn't seem to be tested elsewhere, so it might be best to leave that for later.

### Pattern match warnings

I have found two separate issues with pattern match warnings.

#### Internal constructors

The pattern match warnings are phrased in terms of the internal constructors. For example:

```haskell
basic (ANON{ a = False }) = ()
```

```
    Pattern match(es) are non-exhaustive
    In an equation for `basic':
        Patterns not matched:
            large-anon-0.1.0.0:Data.Record.Anon.Internal.Simple.SimpleRecord
            (large-anon-0.1.0.0:Data.Record.Anon.Internal.Advanced.NoPending _)
            large-anon-0.1.0.0:Data.Record.Anon.Internal.Simple.SimpleRecord
            (large-anon-0.1.0.0:Data.Record.Anon.Internal.Advanced.HasPending _
             _)
   |
   | basic ANON{a = False} = ()
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

This is quite disorienting, when obviously we would the message to be:

```
    Pattern match(es) are non-exhaustive
    In an equation for `basic':
        Patterns not matched:
            ANON { a = True }
```

I'm not sure what can be done about this. There's [GHC issue #20311](https://gitlab.haskell.org/ghc/ghc/-/issues/20311) which is somewhat related.

#### Incorrect warnings

The fact that we use view patterns to desugar the record patterns causes difficulties with pattern match warnings. This is because each view pattern is given by a separate lambda, and GHC has no way to inspect these lambdas to propagate coverage information across matches. For example, the following function causes pattern match warnings to be emitted:

```haskell
warns :: S.Record [ "fld1" := Bool, "fld2" := Int ] -> Int
warns (ANON {fld1 = True}) = 1
warns (ANON {fld1 = False}) = 2
```

In this simple case, if we extract out the view pattern function, we can avoid the pattern match warnings:

```haskell
getter :: S.Record [ "fld1" := Bool, "fld2" := Int ] -> Bool
getter = S.get #fld1

doesn't_warn :: S.Record [ "fld1" := Bool, "fld2" := Int ] -> Int
doesn't_warn (getter -> True) = 1
doesn't_warn (getter -> False) = 2
```

This is because GHC sees that we are using the exact same view function in both cases, and thus combines the coverage information across the two matches.   

However, this won't work when we match on different numbers of fields across the matches, e.g.

```haskell
warns2 :: S.Record [ "fld1" := Bool, "fld2" := Int ] -> Int
warns2 (ANON {fld1 = True}) = 1
warns2 (ANON {fld1 = False, fld2 = i}) = i
```

In this case we would be using two completely different view functions, the first one being `getField #fld1` and the second being `\r -> (getField #fld1 r, getField #fld2 r)`. 

I don't see how to fix this either, unfortunately. I'll ask around for ideas. I think it's unlikely we'll be able to come up with better solutions in the short term. As I think the feature is important, it is probably better to merge it without fixing these issues, as long as we make sure to clearly document these limitations.

Thanks again for your contribution and your patience.

**Comment by sheaf** [comment]
Perhaps the way forward is to change the source plugin to not rewrite patterns on their own, but rather pattern matches.

For example, if we can rewrite

```haskell
foo (ANON { b = False }) = 0
foo (ANON { b = True, i = i}) = i
```

to

```haskell
foo' :: S.Record ["b" := Bool, "i" := Int] -> Int
foo' r
  | False <- get_b
  = 0
  | True <- get_b
  , i <- get_i
  = i
  where
    get_b = S.get #b r
    get_i = S.get #i r
```

then we get exactly the right pattern match warnings (solving the "Incorrect warnings" issue from my previous post, but not the "Internal constructors" issue).

**Comment by sheaf** [comment]
I did some experiments and I think actually we can make the pattern match warnings work correctly as long as we float out the accessors to the top-level. In the source plugin, whenever we come across a pattern `ANON { fld1 = p1, fld2 = p2 }`, we transform the patterns as we do now, except that instead of using `get #fld1` and `get #fld2` for the view patterns, we float those out to the top-level:

```haskell
foo :: S.Record ["b" := Bool, "i" := Int] -> Int
foo (ANON { b = False }) = 0
foo (ANON { b = True, i = i }) = i
```

```haskell
get_b :: RowHasField "b" r a => Record r -> a
get_b = S.get #b
get_i :: RowHasField "i" r a => Record r -> a
get_i = S.get #i

foo :: S.Record ["b" := Bool, "i" := Int] -> Int
foo (get_b -> False) = 0
foo ((\ r -> (get_b r, get_i r)) -> (True, i)) = i
```

This works without any pattern match warnings.

**Comment by sheaf** [comment]
I've filed [GHC bug #21662](https://gitlab.haskell.org/ghc/ghc/-/issues/21662) for this issue with pattern match warnings. I think for the time being we're best off implementing the workaround in https://github.com/well-typed/large-records/pull/111#issuecomment-1139863136. @kana-sama, would you be OK to proceed with that?

**Comment by sheaf** [comment]
To summarise, the issue with pattern match warnings is caused by [GHC bug #21662](https://gitlab.haskell.org/ghc/ghc/-/issues/21662). The pattern match coverage checker doesn't properly handle dictionary arguments. This means that the desugaring of patterns in terms of `getField` causes a problem: the different calls to `getField` are supplied syntactically different `HasField` evidence, and this prevents us from seeing we are using the exact same view pattern across matches.

I'm not sure what can be done without resolving that GHC bug. We can try to extract out the accessors:

```haskell
foo :: S.Record ["b" := Bool, "i" := Int] -> Int
foo ANON{ b = False } = 0
foo ANON { b = True, i = i } = i
```

can be turned into:

```haskell
get_b :: S.Record _r -> _a
get_b = S.get #b
get_i :: S.Record _r -> _a
get_i = S.get #i

foo :: S.Record ["b" := Bool, "i" := Int] -> Int
foo (get_b -> False) = 0
foo ((\ r -> (get_b r, get_i r)) -> (True, i)) = i
```

This uses partial type signatures. This compiles without any pattern match warnings, but I suspect that type inference is worse with this approach.  

We can't use:

```haskell
get_b :: RowHasField "b" r a => S.Record r -> a
get_b = S.get #b
get_i :: RowHasField "i" r a => S.Record r -> a
get_i = S.get #i
```

as these accessors still have a class constraint and we thus run into the same problem.

**Comment by edsko** [comment]
@kana-sama @sheaf what's the status on this?

**Comment by sheaf** [comment]
My opinion is that the issues with pattern match warnings are due to GHC bugs. I have been discussing with Sebastian and I will try to fix them in GHC. It seems reasonable to keep the implementation as it is here, providing a disclaimer that pattern match warnings are likely to be poor because of GHC bugs, rather than add a lot of complexity to the implementation to try to work around these issues.

So I'm quite happy with the patch as it is, provided we document the situation.

**Comment by edsko** [comment]
@kana-sama can you add such a comment? Then I will merge the PR. Thanks for the hard work!

**Comment by kana-sama** [comment]
I found out that for us in Juspay project we need another pattern, that will match any record via getField. So we don't need this solution. And because this solution has some problems, it is better not to merge it, and try to find better solutions, or fix this one.

**Comment by kana-sama** [comment]
@sheaf thanks for such good analysis and review!

**Comment by edsko** [comment]
Closing this since @kana-sama indicated they need something else.

**Pull request closed without merging**
