### PR TITLE
Support RDP _within_ quasi-quotes

### PR DESCRIPTION
**Pull request by edsko**
This is actually exposing a bug somewhere (reported by @kana-sama ). Will need to investigate and fix.

### CODE REVIEW

**Comment by edsko** [comment]
This turns out to be a bug in `haskell-src-meta`. The string

```haskel
Z.getField @'("a","b") foo
```

gets parsed correctly by `haskell-src-exts`, but then `toExp` results in

```
AppE 
  (AppTypeE 
    (VarE Z.getField) 
    (AppT (AppT (PromotedTupleT 2) (LitT (StrTyLit "b"))) (LitT (StrTyLit "a")))
  )
  (VarE foo)
```

Will investigate.

**Comment by avnik** [comment]
@edsko I heard you have a fix for that, could you please mention solution here if/when it will be found?

**Comment by edsko** [comment]
Not yet. I will find one, but unfortunately I am out sick at the moment. This is my first priority once I get back to work though!

**Comment by edsko** [comment]
Since @avnik has already submitted a patch to `haskell-src-meta`, I will leave this as a draft until a new release of `haskell-src-meta` is ready. Holler if that is a problem.

**Comment by edsko** [comment]
Ok, change of plan. The LR side of this is ready and tested. I will merge this once CI is green; then RDP can be used within LR quotes provided that @avnik 's patch is applied to `haskell-src-meta`.

**Pull request merged**
