### PR TITLE
Restore DerivingVia/DerivingNewtype

### PR DESCRIPTION
**Pull request by avnik**
Some stuff from #4 strikes back, and I tried to support all deriving strategies.
(this solution not ideal, and definitely need better naming, so suggestions welcomed)

### CODE REVIEW

**Comment by kana-sama** [comment]
On my opinion `deriving newtype` should be rejected by `large-records`, because it makes no sense to derive newtype instance from data-definition.

**Comment by edsko** [comment]
I'm wondering if this is really the right thing. For `newtype` deriving, if a user defines

```
largeRecord [d|
  data T = MkT { .... }
    deriving newtype ...
  |]
```

they will get an instance for `Vector Any`, like @kana-sama points out; that feels wrong. 

When discussing this with @kana-sama this morning, I thought that the same argument actually also goes for `deriving-via`. After all, deriving-via basically _is_ newtype deriving, you just get the opportunity to specify another newtype in the middle.
_However_, having thought about it some more, I now thing that actually there is a difference. With deriving-via, you must _specify_ something that the type is representationally equal to. So if users would do this, they would need to specify something that is representationally equal to a `Vector Any`. Still not ideal, but at least it would be more explicit.

It still makes me uncomfortable though. Ideally, a `largeRecord` splice does not change semantics. I know that's an ideal we don't quite achieve, but still, in principle at least it should be possible to write code in such a way that it would work whether or not a record is declared as a large record (large-record style generics could in principle be supported for ordinary records). But if we have this deriving-via clause, you'd really be tying the record to its internal representation: if for some reason we discover that a different internal representation would be better, suddenly a `deriving-via` clause somewhere might break -- but that internal representation should be just that -- internal.

So all in all, I'm still not really in favour of supporting either newtype or deriving-via for large-records. But perhaps we should zoom out a bit and ask why do you want these in the first place? Could we solve the problem you have in a different way?

**Comment by edsko** [comment]
Case in point of a PR that changes the internal representation in `large-records`: #43.

**Comment by avnik** [comment]
@edsko we decided to eliminate 2 cases in code, where it was required. So I can withdraw this PR

**Comment by edsko** [comment]
Ok :) If it comes back again, let me know, and we can reconsider.

**Pull request closed without merging**
